# taskOne
## Counting GCF per order

_Date: 04/12/2017_

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/home/savy/Documents/2017_master_internship/GenePredictionTask/Genomes/genomeDownloader/GCA_GCF_insectGenomes.csv')

In [64]:
GCFDict = {'species':[], 'genome_id':[], 'order':[], 'family':[]}

for index in df.index :
    if 'GCF' in df['genome_id'][index]:
        GCFDict['species'].append(df['sp_name'][index])
        GCFDict['genome_id'].append(df['genome_id'][index])
        GCFDict['order'].append(df['order_name'][index])
        GCFDict['family'].append(df['family_name'][index])

In [78]:
GCF_df = pd.DataFrame(GCFDict)
GCF_df.groupby(['order','family']).count()

                                genome_id  species
order        family
Coleoptera   Buprestidae                1        1
             Cerambycidae               1        1
             Curculionidae              1        1
             Nitidulidae                1        1
             Silphidae                  1        1
             Tenebrionidae              1        1
Diptera      Culicidae                  4        4
             Drosophilidae             25       25
             Muscidae                   2        2
             Tephritidae                6        6
Hemiptera    Aleyrodidae                1        1
             Aphididae                  2        2
             Cimicidae                  1        1
             Pentatomidae               1        1
             Psyllidae                  1        1
Hymenoptera  Agaonidae                  1        1
             Apidae                     9        9
             Braconidae                 3        3
             Cephidae                   1        1
             Diprionidae                1        1
             Encyrtidae                 1        1
             Formicidae                18       18
             Halictidae                 1        1
             Megachilidae               1        1
             Orussidae                  1        1
             Pteromalidae               1        1
             Tenthredinidae             1        1
             Trichogrammatidae          1        1
             Vespidae                   2        2
Lepidoptera  Bombycidae                 1        1
             Papilionidae               3        3
             Plutellidae                1        1
             Pyralidae                  1        1
Phthiraptera Pediculidae                1        1

In [72]:
GCADict = {'species':[], 'genome_id':[], 'order':[], 'family':[]}

for index in df.index :
    if 'GCA' in df['genome_id'][index]:
        GCADict['species'].append(df['sp_name'][index])
        GCADict['genome_id'].append(df['genome_id'][index])
        GCADict['order'].append(df['order_name'][index])
        GCADict['family'].append(df['family_name'][index])

In [77]:
GCA_df = pd.DataFrame(GCADict)
GCA_df.groupby(['order','family']).count()

                             genome_id  species
order        family
Blattodea    Ectobiidae              1        1
             Termitidae              1        1
             Termopsidae             1        1
Coleoptera   Chrysomelidae           1        1
             Cupedidae               1        1
             Curculionidae           1        1
             Scarabaeidae            2        2
Collembola   Entomobryidae           1        1
Diplura      Japygidae               1        1
Diptera      Agromyzidae             1        1
             Asilidae                2        2
             Calliphoridae           4        4
             Cecidomyiidae           1        1
             Chaoboridae             2        2
             Chironomidae            4        4
             Culicidae              23       23
             Diopsidae               2        2
             Dolichopodidae          1        1
             Drosophilidae           6        6
             Ephydridae              2        2
             Glossinidae             7        7
             Phoridae                2        2
             Psychodidae             3        3
             Sarcophagidae           2        2
             Scatopsidae             1        1
             Sepsidae                1        1
             Stratiomyidae           1        1
             Syrphidae               1        1
             Tephritidae             4        4
             Tipulidae               1        1
...                                ...      ...
Hemiptera    Lygaeidae               1        1
             Pentatomidae            1        1
             Pseudococcidae          6        6
             Psyllidae               1        1
             Reduviidae              1        1
Hymenoptera  Agaonidae               1        1
             Apidae                  2        2
             Braconidae              1        1
             Figitidae               1        1
             Formicidae              1        1
             Halictidae              1        1
             Pteromalidae            2        2
Lepidoptera  Crambidae               1        1
             Geometridae             1        1
             Hesperiidae             1        1
             Lycaenidae              1        1
             Noctuidae               1        1
             Nymphalidae            23       23
             Papilionidae            1        1
             Pieridae                2        2
             Sphingidae              1        1
Odonata      Libellulidae            1        1
Orthoptera   Acrididae               1        1
Phasmatodea  Timematidae             1        1
Phthiraptera Pediculidae             1        1
Plecoptera   Nemouridae              1        1
             Perlodidae              1        1
Strepsiptera Mengenillidae           1        1
Thysanoptera Thripidae               1        1
Trichoptera  Limnephilidae           1        1

[69 rows x 2 columns]