# task_One 
## Finding Orders and Families numbers for insects

Date: 03/10/2017

In [8]:
'''
From build_insectGenomesInfos.py
'''

import pandas as pd
pathcsv="/home/savandara/Documents/Internship/2017_master_internship/genomeDownloader/curated_insectGenomesInfos.csv"

df = pd.read_csv(pathcsv) 
df

     GCA_000349125.1
0    GCA_000441895.2
1    GCA_000349065.1
2    GCA_000349185.1
3    GCA_000473845.2
4    GCA_000473375.1
5    GCA_000349085.1
6    GCA_000209185.1
7    GCA_001014445.1
8    GCA_000005925.1
9    GCA_000005115.1
10   GCA_000236285.2
11   GCA_000224215.2
12   GCA_000236325.2
13   GCA_000001215.4
14   GCA_000259055.1
15   GCA_000005215.1
16   GCA_000005135.1
17   GCA_000005975.1
18   GCA_000220665.2
19   GCA_000224195.2
20   GCA_000236305.2
21   GCA_000233415.2
22   GCA_000224235.2
23   GCA_000269505.2
24   GCA_000001765.2
25   GCA_000005195.1
26   GCA_000298335.1
27   GCA_000005155.1
28   GCA_000005175.1
29   GCA_000005245.1
30   GCA_000371365.1
31   GCA_001594075.1
32   GCA_001594045.1
33   GCA_000143395.2
34   GCA_000204515.1
35   GCA_000572035.2
36   GCA_000217595.1
37  GCA_000005575.1
38   GCA_000209185.1
39   GCA_000004015.3
40  GCA_000347755.2
41   GCA_000002325.2
42   GCA_000188075.1
43  GCA_001313835.1
44   GCA_000441895.2
45  GCA_000789215.2
46   GCA_001313835.1

In [53]:
result = df.groupby(["Order name", "Family name", "Species name"]).count()
result

                                                               Species id  \
Order name   Family name   Species name
Blattodea    Ectobiidae    Blattella germanica                          1
             Termitidae    Nasutitermes exitiosus                       1
             Termopsidae   Zootermopsis nevadensis                      1
Coleoptera   Buprestidae   Agrilus planipennis                          1
             Cerambycidae  Anoplophora glabripennis                     1
             Chrysomelidae Leptinotarsa decemlineata                    1
             Cupedidae     Priacma serrata                              1
             Curculionidae Dendroctonus ponderosae                      1
                           Hypothenemus hampei                          1
             Nitidulidae   Aethina tumida                               1
             Scarabaeidae  Onthophagus taurus                           1
                           Oryctes borbonicus                           1
             Silphidae     Nicrophorus vespilloides                     1
             Tenebrionidae Tribolium castaneum                          1
Collembola   Entomobryidae Orchesella cincta                            1
Diplura      Japygidae     Catajapyx aquilonaris                        1
Diptera      Agromyzidae   Liriomyza trifolii                           1
             Asilidae      Holcocephala fusca                           1
                           Proctacanthus coquilletti                    1
             Calliphoridae Calliphora vicina                            1
                           Lucilia cuprina                              1
                           Lucilia sericata                             1
                           Phormia regina                               1
             Cecidomyiidae Mayetiola destructor                         1
             Chaoboridae   Chaoborus trivitattus                        1
                           Mochlonyx cinctipes                          1
             Chironomidae  Belgica antarctica                           1
                           Chironomus riparius                          1
                           Chironomus tentans                           1
                           Clunio marinus                               1
...                                                                   ...
Lepidoptera  Nymphalidae   Heliconius melpomene malleti                 1
                           Heliconius melpomene melpomene               1
                           Heliconius numata arcuella                   1
                           Heliconius numata silvana                    1
                           Heliconius numata tarapotensis               1
                           Heliconius pardalinus sergestus              1
                           Heliconius pardalinus ssp. JD-2011           1
                           Heliconius timareta                          1
                           Heliconius timareta ssp. JD-2011             1
                           Heliconius timareta ssp. NG-2008             1
                           Heliconius timareta timareta                 1
                           Melitaea cinxia                              1
             Papilionidae  Papilio glaucus                              1
                           Papilio machaon                              1
                           Papilio polytes                              1
                           Papilio xuthus                               1
             Pieridae      Phoebis sennae                               1
                           Pieris rapae                                 1
             Plutellidae   Plutella xylostella                          1
             Pyralidae     Amyelois transitella                         1
             Sphingidae    Manduca sexta                                1
Odonata      Libellulidae  Ladona fulva                                 1
Orthoptera   Acrididae     Locusta migratoria                           1
Phasmatodea  Timematidae   Timema cristinae                             1
Phthiraptera Pediculidae   Pediculus humanus corporis                   1
Plecoptera   Nemouridae    Amphinemura sulcicollis                      1
             Perlodidae    Isoperla grammatica                          1
Strepsiptera Mengenillidae Mengenilla moldrzyki                         1
Thysanoptera Thripidae     Frankliniella occidentalis                   1
Trichoptera  Limnephilidae Limnephilus lunatus                          1

                                                               Family id  \
Order name   Family name   Species name
Blattodea    Ectobiidae    Blattella germanica                         1
             Termitidae    Nasutitermes exitiosus                      1
             Termopsidae   Zootermopsis nevadensis                     1
Coleoptera   Buprestidae   Agrilus planipennis                         1
             Cerambycidae  Anoplophora glabripennis                    1
             Chrysomelidae Leptinotarsa decemlineata                   1
             Cupedidae     Priacma serrata                             1
             Curculionidae Dendroctonus ponderosae                     1
                           Hypothenemus hampei                         1
             Nitidulidae   Aethina tumida                              1
             Scarabaeidae  Onthophagus taurus                          1
                           Oryctes borbonicus                          1
             Silphidae     Nicrophorus vespilloides                    1
             Tenebrionidae Tribolium castaneum                         1
Collembola   Entomobryidae Orchesella cincta                           1
Diplura      Japygidae     Catajapyx aquilonaris                       1
Diptera      Agromyzidae   Liriomyza trifolii                          1
             Asilidae      Holcocephala fusca                          1
                           Proctacanthus coquilletti                   1
             Calliphoridae Calliphora vicina                           1
                           Lucilia cuprina                             1
                           Lucilia sericata                            1
                           Phormia regina                              1
             Cecidomyiidae Mayetiola destructor                        1
             Chaoboridae   Chaoborus trivitattus                       1
                           Mochlonyx cinctipes                         1
             Chironomidae  Belgica antarctica                          1
                           Chironomus riparius                         1
                           Chironomus tentans                          1
                           Clunio marinus                              1
...                                                                  ...
Lepidoptera  Nymphalidae   Heliconius melpomene malleti                1
                           Heliconius melpomene melpomene              1
                           Heliconius numata arcuella                  1
                           Heliconius numata silvana                   1
                           Heliconius numata tarapotensis              1
                           Heliconius pardalinus sergestus             1
                           Heliconius pardalinus ssp. JD-2011          1
                           Heliconius timareta                         1
                           Heliconius timareta ssp. JD-2011            1
                           Heliconius timareta ssp. NG-2008            1
                           Heliconius timareta timareta                1
                           Melitaea cinxia                             1
             Papilionidae  Papilio glaucus                             1
                           Papilio machaon                             1
                           Papilio polytes                             1
                           Papilio xuthus                              1
             Pieridae      Phoebis sennae                              1
                           Pieris rapae                                1
             Plutellidae   Plutella xylostella                         1
             Pyralidae     Amyelois transitella                        1
             Sphingidae    Manduca sexta                               1
Odonata      Libellulidae  Ladona fulva                                1
Orthoptera   Acrididae     Locusta migratoria                          1
Phasmatodea  Timematidae   Timema cristinae                            1
Phthiraptera Pediculidae   Pediculus humanus corporis                  1
Plecoptera   Nemouridae    Amphinemura sulcicollis                     1
             Perlodidae    Isoperla grammatica                         1
Strepsiptera Mengenillidae Mengenilla moldrzyki                        1
Thysanoptera Thripidae     Frankliniella occidentalis                  1
Trichoptera  Limnephilidae Limnephilus lunatus                         1

                                                               Order id  \
Order name   Family name   Species name
Blattodea    Ectobiidae    Blattella germanica                        1
             Termitidae    Nasutitermes exitiosus                     1
             Termopsidae   Zootermopsis nevadensis                    1
Coleoptera   Buprestidae   Agrilus planipennis                        1
             Cerambycidae  Anoplophora glabripennis                   1
             Chrysomelidae Leptinotarsa decemlineata                  1
             Cupedidae     Priacma serrata                            1
             Curculionidae Dendroctonus ponderosae                    1
                           Hypothenemus hampei                        1
             Nitidulidae   Aethina tumida                             1
             Scarabaeidae  Onthophagus taurus                         1
                           Oryctes borbonicus                         1
             Silphidae     Nicrophorus vespilloides                   1
             Tenebrionidae Tribolium castaneum                        1
Collembola   Entomobryidae Orchesella cincta                          1
Diplura      Japygidae     Catajapyx aquilonaris                      1
Diptera      Agromyzidae   Liriomyza trifolii                         1
             Asilidae      Holcocephala fusca                         1
                           Proctacanthus coquilletti                  1
             Calliphoridae Calliphora vicina                          1
                           Lucilia cuprina                            1
                           Lucilia sericata                           1
                           Phormia regina                             1
             Cecidomyiidae Mayetiola destructor                       1
             Chaoboridae   Chaoborus trivitattus                      1
                           Mochlonyx cinctipes                        1
             Chironomidae  Belgica antarctica                         1
                           Chironomus riparius                        1
                           Chironomus tentans                         1
                           Clunio marinus                             1
...                                                                 ...
Lepidoptera  Nymphalidae   Heliconius melpomene malleti               1
                           Heliconius melpomene melpomene             1
                           Heliconius numata arcuella                 1
                           Heliconius numata silvana                  1
                           Heliconius numata tarapotensis             1
                           Heliconius pardalinus sergestus            1
                           Heliconius pardalinus ssp. JD-2011         1
                           Heliconius timareta                        1
                           Heliconius timareta ssp. JD-2011           1
                           Heliconius timareta ssp. NG-2008           1
                           Heliconius timareta timareta               1
                           Melitaea cinxia                            1
             Papilionidae  Papilio glaucus                            1
                           Papilio machaon                            1
                           Papilio polytes                            1
                           Papilio xuthus                             1
             Pieridae      Phoebis sennae                             1
                           Pieris rapae                               1
             Plutellidae   Plutella xylostella                        1
             Pyralidae     Amyelois transitella                       1
             Sphingidae    Manduca sexta                              1
Odonata      Libellulidae  Ladona fulva                               1
Orthoptera   Acrididae     Locusta migratoria                         1
Phasmatodea  Timematidae   Timema cristinae                           1
Phthiraptera Pediculidae   Pediculus humanus corporis                 1
Plecoptera   Nemouridae    Amphinemura sulcicollis                    1
             Perlodidae    Isoperla grammatica                        1
Strepsiptera Mengenillidae Mengenilla moldrzyki                       1
Thysanoptera Thripidae     Frankliniella occidentalis                 1
Trichoptera  Limnephilidae Limnephilus lunatus                        1

                                                               Acession number
Order name   Family name   Species name
Blattodea    Ectobiidae    Blattella germanica                               1
             Termitidae    Nasutitermes exitiosus                            1
             Termopsidae   Zootermopsis nevadensis                           1
Coleoptera   Buprestidae   Agrilus planipennis                               1
             Cerambycidae  Anoplophora glabripennis                          1
             Chrysomelidae Leptinotarsa decemlineata                         1
             Cupedidae     Priacma serrata                                   1
             Curculionidae Dendroctonus ponderosae                           1
                           Hypothenemus hampei                               1
             Nitidulidae   Aethina tumida                                    1
             Scarabaeidae  Onthophagus taurus                                1
                           Oryctes borbonicus                                1
             Silphidae     Nicrophorus vespilloides                          1
             Tenebrionidae Tribolium castaneum                               1
Collembola   Entomobryidae Orchesella cincta                                 1
Diplura      Japygidae     Catajapyx aquilonaris                             1
Diptera      Agromyzidae   Liriomyza trifolii                                1
             Asilidae      Holcocephala fusca                                1
                           Proctacanthus coquilletti                         1
             Calliphoridae Calliphora vicina                                 1
                           Lucilia cuprina                                   1
                           Lucilia sericata                                  1
                           Phormia regina                                    1
             Cecidomyiidae Mayetiola destructor                              1
             Chaoboridae   Chaoborus trivitattus                             1
                           Mochlonyx cinctipes                               1
             Chironomidae  Belgica antarctica                                1
                           Chironomus riparius                               1
                           Chironomus tentans                                1
                           Clunio marinus                                    1
...                                                                        ...
Lepidoptera  Nymphalidae   Heliconius melpomene malleti                      1
                           Heliconius melpomene melpomene                    1
                           Heliconius numata arcuella                        1
                           Heliconius numata silvana                         1
                           Heliconius numata tarapotensis                    1
                           Heliconius pardalinus sergestus                   1
                           Heliconius pardalinus ssp. JD-2011                1
                           Heliconius timareta                               1
                           Heliconius timareta ssp. JD-2011                  1
                           Heliconius timareta ssp. NG-2008                  1
                           Heliconius timareta timareta                      1
                           Melitaea cinxia                                   1
             Papilionidae  Papilio glaucus                                   1
                           Papilio machaon                                   1
                           Papilio polytes                                   1
                           Papilio xuthus                                    1
             Pieridae      Phoebis sennae                                    1
                           Pieris rapae                                      1
             Plutellidae   Plutella xylostella                               1
             Pyralidae     Amyelois transitella                              1
             Sphingidae    Manduca sexta                                     1
Odonata      Libellulidae  Ladona fulva                                      1
Orthoptera   Acrididae     Locusta migratoria                                1
Phasmatodea  Timematidae   Timema cristinae                                  1
Phthiraptera Pediculidae   Pediculus humanus corporis                        1
Plecoptera   Nemouridae    Amphinemura sulcicollis                           1
             Perlodidae    Isoperla grammatica                               1
Strepsiptera Mengenillidae Mengenilla moldrzyki                              1
Thysanoptera Thripidae     Frankliniella occidentalis                        1
Trichoptera  Limnephilidae Limnephilus lunatus                               1

[246 rows x 4 columns]

## Proposition of a model organism for each order

- Order: Blattodea $\rightarrow$ Family number: 3 $\Rightarrow$ __Meta HMM sur 3 ?__
- Order: Coleoptera $\rightarrow$ Family number: 8 $\Rightarrow$ __Meta HMM sur 4 ?__ On a un organisme modèle
- Order: Collembola $\rightarrow$ Family number: 1 $\Rightarrow$ __Orchesella cincta__
- Order: Diplura $\rightarrow$ Family number: 1 $\Rightarrow$ __Catajapyx aquilonaris__
- Order: Diptera $\rightarrow$ Family number: 23 $\Rightarrow$ __Drosophila Melanogaster__
- Order: Ephemeroptera $\rightarrow$ Family number: 2 $\Rightarrow$ __Meta HMM sur 2 ?__
- Order: Hemiptera $\rightarrow$ Family number: 12 $\Rightarrow$ __Meta HMM sur 6 ?__
- Order: Hymenoptera $\rightarrow$ Family number: 15 $\Rightarrow$ __Meta HMM sur abeille, guepe et fourmi ?__ Nassonia visperis
- Order: Lepidoptera $\rightarrow$ Family number: 12 $\Rightarrow$ __Meta HMM sur 6 ?__ Papillon
- Order: Odonata $\rightarrow$ Family number: 1 $\Rightarrow$ __Ladona fulva__
- Order: Orthoptera $\rightarrow$ Family number: 1 $\Rightarrow$ __Locusta migratoria__
- Order: Phasmatodea $\rightarrow$ Family number: 1 $\Rightarrow$ __Timema cristinae__
- Order: Phthiraptera $\rightarrow$ Family number: 1 $\Rightarrow$ __Pediculus humanus corporis__
- Order: Plecoptera $\rightarrow$ Family number: 2 $\Rightarrow$ __Meta HMM sur 2 ?__
- Order: Strepsiptera $\rightarrow$ Family number: 1 $\Rightarrow$ __Mengenilla 
- Order: Thysanoptera $\rightarrow$ Family number: 1 $\Rightarrow$ __Frankliniella occidentalis__
- Order: Trichoptera $\rightarrow$ Family number: 1 $\Rightarrow$ __Limnephilus lunatus__

## TO DO
Determine if these genomes have already a GFF file or not (to pass augustus-one step)